# Generated by Django 5.1.6 on 2025-04-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='away_score',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='home_score',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
    ]
