# Generated by Django 5.1.6 on 2025-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_winnerpick_away_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='status',
            field=models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Tie', 'Tie')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='week_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick1',
            name='status',
            field=models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Tie', 'Tie')], max_length=6, null=True),
        ),
    ]
