# Generated by Django 5.1.6 on 2025-06-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_winnerpick_actual_winner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winnerpick',
            options={'ordering': ['-week_number', 'players']},
        ),
        migrations.AlterModelOptions(
            name='winnerpick1',
            options={'ordering': ['-week_number', 'players']},
        ),
        migrations.RenameField(
            model_name='winnerpick1',
            old_name='player',
            new_name='players',
        ),
        migrations.RenameField(
            model_name='winnerselect',
            old_name='player',
            new_name='players',
        ),
        migrations.RemoveField(
            model_name='winnerpick',
            name='player',
        ),
        migrations.AddField(
            model_name='winnerpick',
            name='players',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara'), ('Stefaun', 'Stefaun')], default='Mom', max_length=200, null=True),
        ),
    ]
