# Generated by Django 5.1.6 on 2025-02-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_home_away_week_number'),
        ('teams', '0004_winnerselect'),
    ]

    operations = [
    ]
