# Generated by Django 5.1.6 on 2025-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_merge_20250218_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerpick',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(blank=True),
        ),
    ]
