# Generated by Django 5.1.6 on 2025-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_winnerpick_options_alter_winnerpick1_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WinnerPick1',
        ),
        migrations.AlterModelOptions(
            name='winnerpick',
            options={'ordering': ['-week_number', 'player']},
        ),
        migrations.RenameField(
            model_name='winnerselect',
            old_name='players',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='winnerpick',
            name='players',
        ),
        migrations.AddField(
            model_name='winnerpick',
            name='player',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara'), ('Stefaun', 'Stefaun')], max_length=200, null=True),
        ),
    ]
