# Generated by Django 5.1.6 on 2025-06-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_delete_winnerpick1_alter_winnerpick_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='player',
            field=models.CharField(blank=True, choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara'), ('Stefaun', 'Stefaun')], max_length=200, null=True),
        ),
    ]
