# Generated by Django 5.1.6 on 2025-02-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_winnerpick_year_alter_home_away_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
