# Generated by Django 5.1.6 on 2025-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_winnerpick_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='player',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara'), ('Stefaun', 'Stefaun')], max_length=200, null=True),
        ),
    ]
