# Generated by Django 5.1.6 on 2025-02-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_home_away_week_number'),
        ('teams', '0008_alter_winnerpick_player'),
    ]

    operations = [
    ]
