# Generated by Django 5.1.6 on 2025-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_merge_20250218_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='actual_winner',
            field=models.CharField(choices=[('away', 'away'), ('home', 'home')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='selected_pick',
            field=models.CharField(choices=[('away', 'away'), ('home', 'home')], max_length=250, null=True),
        ),
    ]
