# Generated by Django 5.1.6 on 2025-03-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_delete_winnerpick10_delete_winnerpick11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='actual_winner',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='selected_pick',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick1',
            name='actual_winner',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick1',
            name='selected_pick',
            field=models.CharField(choices=[('Away', 'Away'), ('Home', 'Home')], max_length=250, null=True),
        ),
    ]
